name: Install Sparta package

on: workflow_dispatch

jobs:
  install-sparta-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/

    - name: Install Sparta package
      run: yarn add @fewlinesco/sparta
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Commit new version of Sparta package
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        git add yarn.lock
        git config --global user.name "${{ env.USER_NAME }}"
        git config --global user.email "${{ env.USER_EMAIL }}"
        git commit -m "Updating Sparta package"
        git push
